export interface CareerPageTarget {
  company: string;
  slug: string;
  ats: 'greenhouse' | 'lever' | 'workday' | 'custom';
  website?: string;
}

// Workday + Custom ATS companies require Playwright — Phase 5.
// This file contains all Greenhouse + Lever companies (JSON APIs, no browser needed).

export const CAREER_PAGES: CareerPageTarget[] = [

  // ── Israeli Fintech & Payments ──────────────────────────────────────────
  { company: 'Melio',          slug: 'melio',          ats: 'greenhouse', website: 'https://meliopayments.com' },
  { company: 'Rapyd',          slug: 'rapyd',          ats: 'lever',      website: 'https://rapyd.net' },
  { company: 'Payoneer',       slug: 'payoneer',       ats: 'greenhouse', website: 'https://payoneer.com' },
  { company: 'Pagaya',         slug: 'pagaya',         ats: 'greenhouse', website: 'https://pagaya.com' },
  { company: 'eToro',          slug: 'etoro',          ats: 'greenhouse', website: 'https://etoro.com' },
  { company: 'Tipalti',        slug: 'tipalti',        ats: 'greenhouse', website: 'https://tipalti.com' },
  { company: 'Papaya Global',  slug: 'papayaglobal',   ats: 'greenhouse', website: 'https://papayaglobal.com' },
  { company: 'Riskified',      slug: 'riskified',      ats: 'greenhouse', website: 'https://riskified.com' },
  { company: 'Nuvei',          slug: 'nuvei',          ats: 'greenhouse', website: 'https://nuvei.com' },
  { company: 'Fundbox',        slug: 'fundbox',        ats: 'greenhouse', website: 'https://fundbox.com' },
  { company: 'Global-e',       slug: 'global-e',       ats: 'greenhouse', website: 'https://global-e.com' },
  { company: 'Rewire',         slug: 'rewire',         ats: 'lever',      website: 'https://rewire.to' },
  { company: 'Tabby',          slug: 'tabby',          ats: 'greenhouse', website: 'https://tabby.ai' },
  { company: 'Check',          slug: 'check',          ats: 'greenhouse', website: 'https://checkhq.com' },
  { company: 'Stampli',        slug: 'stampli',        ats: 'greenhouse', website: 'https://stampli.com' },
  { company: 'BlueSnap',       slug: 'bluesnap',       ats: 'greenhouse', website: 'https://bluesnap.com' },
  { company: 'Mesh Payments',  slug: 'meshpayments',   ats: 'greenhouse', website: 'https://meshpayments.com' },
  { company: 'Payrails',       slug: 'payrails',       ats: 'greenhouse', website: 'https://payrails.com' },
  { company: 'FundGuard',      slug: 'fundguard',      ats: 'greenhouse', website: 'https://fundguard.com' },
  { company: 'Earnix',         slug: 'earnix',         ats: 'greenhouse', website: 'https://earnix.com' },
  { company: 'Nayax',          slug: 'nayax',          ats: 'greenhouse', website: 'https://nayax.com' },
  { company: 'Sentinels',      slug: 'sentinels',      ats: 'greenhouse', website: 'https://sentinels.co' },
  { company: 'Justt',          slug: 'justt',          ats: 'greenhouse', website: 'https://justt.ai' },
  { company: 'Appcharge',      slug: 'appcharge',      ats: 'greenhouse', website: 'https://appcharge.com' },
  { company: 'Okoora',         slug: 'okoora',         ats: 'greenhouse', website: 'https://okoora.com' },
  { company: 'Obligo',         slug: 'obligo',         ats: 'greenhouse', website: 'https://obligo.com' },
  { company: 'Lama AI',        slug: 'lamaai',         ats: 'greenhouse', website: 'https://lama.ai' },

  // ── Israeli High-Tech & SaaS ────────────────────────────────────────────
  { company: 'monday.com',     slug: 'mondaydotcom',   ats: 'greenhouse', website: 'https://monday.com' },
  { company: 'Lemonade',       slug: 'lemonade',       ats: 'greenhouse', website: 'https://lemonade.com' },
  { company: 'Wix',            slug: 'wix',            ats: 'greenhouse', website: 'https://wix.com' },
  { company: 'Fiverr',         slug: 'fiverr',         ats: 'greenhouse', website: 'https://fiverr.com' },
  { company: 'Lusha',          slug: 'lusha',          ats: 'greenhouse', website: 'https://lusha.com' },
  { company: 'Kaltura',        slug: 'kaltura',        ats: 'greenhouse', website: 'https://kaltura.com' },
  { company: 'Silverfort',     slug: 'silverfort',     ats: 'greenhouse', website: 'https://silverfort.com' },
  { company: 'Gett',           slug: 'gett',           ats: 'greenhouse', website: 'https://gett.com' },
  { company: 'Trigo',          slug: 'trigovision',    ats: 'greenhouse', website: 'https://trigo.ai' },
  { company: 'Orca Security',  slug: 'orcasecurity',   ats: 'greenhouse', website: 'https://orca.security' },
  { company: 'Snyk',           slug: 'snyk',           ats: 'greenhouse', website: 'https://snyk.io' },
  { company: 'Cloudinary',     slug: 'cloudinary',     ats: 'greenhouse', website: 'https://cloudinary.com' },
  { company: 'SimilarWeb',     slug: 'similarweb',     ats: 'greenhouse', website: 'https://similarweb.com' },
  { company: 'AppsFlyer',      slug: 'appsflyer',      ats: 'greenhouse', website: 'https://appsflyer.com' },
  { company: 'IronSource',     slug: 'ironsource',     ats: 'greenhouse', website: 'https://is.com' },
  { company: 'Outbrain',       slug: 'outbrain',       ats: 'greenhouse', website: 'https://outbrain.com' },
  { company: 'Taboola',        slug: 'taboola',        ats: 'greenhouse', website: 'https://taboola.com' },
  { company: 'WalkMe',         slug: 'walkme',         ats: 'greenhouse', website: 'https://walkme.com' },
  { company: 'Playtika',       slug: 'playtika',       ats: 'greenhouse', website: 'https://playtika.com' },
  { company: 'Skai',           slug: 'skai',           ats: 'greenhouse', website: 'https://skai.io' },
  { company: 'Bringg',         slug: 'bringg',         ats: 'greenhouse', website: 'https://bringg.com' },
  { company: 'Lightricks',     slug: 'lightricks',     ats: 'greenhouse', website: 'https://lightricks.com' },
  { company: 'ActiveFence',    slug: 'activefence',    ats: 'greenhouse', website: 'https://activefence.com' },
  { company: 'Cybereason',     slug: 'cybereason',     ats: 'greenhouse', website: 'https://cybereason.com' },
  { company: 'Gong',           slug: 'gong',           ats: 'greenhouse', website: 'https://gong.io' },
  { company: 'HiBob',          slug: 'hibob',          ats: 'greenhouse', website: 'https://hibob.com' },
  { company: 'Zesty',          slug: 'zesty',          ats: 'greenhouse', website: 'https://zesty.io' },
  { company: 'Syte',           slug: 'syte',           ats: 'greenhouse', website: 'https://syte.ai' },
  { company: 'Buildots',       slug: 'buildots',       ats: 'greenhouse', website: 'https://buildots.com' },
  { company: 'Wiliot',         slug: 'wiliot',         ats: 'greenhouse', website: 'https://wiliot.com' },
  { company: 'Namogoo',        slug: 'namogoo',        ats: 'greenhouse', website: 'https://namogoo.com' },
  { company: 'Connecteam',     slug: 'connecteam',     ats: 'greenhouse', website: 'https://connecteam.com' },
  { company: 'Elementor',      slug: 'elementor',      ats: 'greenhouse', website: 'https://elementor.com' },
  { company: 'Guesty',         slug: 'guesty',         ats: 'greenhouse', website: 'https://guesty.com' },
  { company: 'Credorax',       slug: 'credorax',       ats: 'greenhouse', website: 'https://credorax.com' },

  // ── Israeli VC (Greenhouse only) ────────────────────────────────────────
  { company: 'Insight Partners', slug: 'insightpartners', ats: 'greenhouse', website: 'https://insightpartners.com' },

  // ── French & European Fintech (Greenhouse) ──────────────────────────────
  { company: 'Qonto',          slug: 'qonto',          ats: 'greenhouse', website: 'https://qonto.com' },
  { company: 'Alan',           slug: 'alan',           ats: 'greenhouse', website: 'https://alan.com' },
  { company: 'Spendesk',       slug: 'spendesk',       ats: 'greenhouse', website: 'https://spendesk.com' },
  { company: 'Payfit',         slug: 'payfit',         ats: 'greenhouse', website: 'https://payfit.com' },
  { company: 'Swile',          slug: 'swile',          ats: 'greenhouse', website: 'https://swile.co' },
  { company: 'Alma',           slug: 'alma',           ats: 'greenhouse', website: 'https://almapay.com' },
  { company: 'Pigment',        slug: 'pigment',        ats: 'greenhouse', website: 'https://pigment.app' },
  { company: 'Yousign',        slug: 'yousign',        ats: 'greenhouse', website: 'https://yousign.com' },
  { company: 'Agicap',         slug: 'agicap',         ats: 'greenhouse', website: 'https://agicap.com' },
  { company: 'Shine',          slug: 'shine',          ats: 'greenhouse', website: 'https://shine.fr' },
  { company: 'Swan',           slug: 'swan',           ats: 'greenhouse', website: 'https://swan.io' },
  { company: 'Memo Bank',      slug: 'memobank',       ats: 'greenhouse', website: 'https://memo.bank' },
  { company: 'Defacto',        slug: 'defacto',        ats: 'greenhouse', website: 'https://defacto.fr' },
  { company: 'Pleo',           slug: 'pleo',           ats: 'greenhouse', website: 'https://pleo.io' },
  { company: 'Moss',           slug: 'moss',           ats: 'greenhouse', website: 'https://getmoss.com' },
  { company: 'Billie',         slug: 'billie',         ats: 'greenhouse', website: 'https://billie.io' },
  { company: 'Mondu',          slug: 'mondu',          ats: 'greenhouse', website: 'https://mondu.ai' },
  { company: 'Liberis',        slug: 'liberis',        ats: 'greenhouse', website: 'https://liberis.com' },
  { company: 'Modulr',         slug: 'modulr',         ats: 'greenhouse', website: 'https://modulrfinance.com' },
  { company: 'Griffin',        slug: 'griffin',        ats: 'greenhouse', website: 'https://griffin.com' },
  { company: 'Primer',         slug: 'primer',         ats: 'greenhouse', website: 'https://primer.io' },
  { company: 'Payhawk',        slug: 'payhawk',        ats: 'greenhouse', website: 'https://payhawk.com' },
  { company: 'Soldo',          slug: 'soldo',          ats: 'greenhouse', website: 'https://soldo.com' },
  { company: 'Volt',           slug: 'volt',           ats: 'greenhouse', website: 'https://volt.io' },
  { company: 'Yapily',         slug: 'yapily',         ats: 'greenhouse', website: 'https://yapily.com' },

  // ── French & European Fintech (Lever) ───────────────────────────────────
  { company: 'Ledger',         slug: 'ledger',         ats: 'lever',      website: 'https://ledger.com' },
  { company: 'Pennylane',      slug: 'pennylane',      ats: 'lever',      website: 'https://pennylane.com' },
  { company: 'Lydia',          slug: 'lydia',          ats: 'lever',      website: 'https://lydia-app.com' },
  { company: 'Hokodo',         slug: 'hokodo',         ats: 'lever',      website: 'https://hokodo.co' },
  { company: 'Fintecture',     slug: 'fintecture',     ats: 'lever',      website: 'https://fintecture.com' },
  { company: 'Doctrine',       slug: 'doctrine',       ats: 'lever',      website: 'https://doctrine.fr' },
  { company: 'Indy',           slug: 'indyapp',        ats: 'lever',      website: 'https://indy.fr' },
  { company: 'Karmen',         slug: 'karmen',         ats: 'lever',      website: 'https://karmen.io' },
  { company: 'Solarisbank',    slug: 'solarisbank',    ats: 'lever',      website: 'https://solarisgroup.com' },

  // ── Global Fintech & Payments ────────────────────────────────────────────
  { company: 'Wise',           slug: 'wise',           ats: 'greenhouse', website: 'https://wise.com' },
  { company: 'Checkout.com',   slug: 'checkoutcom',    ats: 'greenhouse', website: 'https://checkout.com' },
  { company: 'Airwallex',      slug: 'airwallex',      ats: 'greenhouse', website: 'https://airwallex.com' },
  { company: 'Deel',           slug: 'deel',           ats: 'greenhouse', website: 'https://deel.com' },
  { company: 'Ripple',         slug: 'ripple',         ats: 'greenhouse', website: 'https://ripple.com' },
  { company: 'Stripe',         slug: 'stripe',         ats: 'greenhouse', website: 'https://stripe.com' },
  { company: 'Brex',           slug: 'brex',           ats: 'greenhouse', website: 'https://brex.com' },
  { company: 'Marqeta',        slug: 'marqeta',        ats: 'greenhouse', website: 'https://marqeta.com' },
  { company: 'Plaid',          slug: 'plaid',          ats: 'greenhouse', website: 'https://plaid.com' },
  { company: 'Nium',           slug: 'nium',           ats: 'greenhouse', website: 'https://nium.com' },
  { company: 'Flywire',        slug: 'flywire',        ats: 'greenhouse', website: 'https://flywire.com' },
  { company: 'dLocal',         slug: 'dlocal',         ats: 'greenhouse', website: 'https://dlocal.com' },
  { company: 'Paysend',        slug: 'paysend',        ats: 'greenhouse', website: 'https://paysend.com' },
  { company: 'Currencycloud',  slug: 'currencycloud',  ats: 'greenhouse', website: 'https://currencycloud.com' },
  { company: 'Ebury',          slug: 'ebury',          ats: 'greenhouse', website: 'https://ebury.com' },
  { company: 'Mambu',          slug: 'mambu',          ats: 'greenhouse', website: 'https://mambu.com' },
  { company: 'Thought Machine', slug: 'thoughtmachine', ats: 'greenhouse', website: 'https://thoughtmachine.net' },
  { company: 'Klarna',         slug: 'klarna',         ats: 'greenhouse', website: 'https://klarna.com' },
  { company: 'Revolut',        slug: 'revolut',        ats: 'greenhouse', website: 'https://revolut.com' },
  { company: 'N26',            slug: 'n26',            ats: 'greenhouse', website: 'https://n26.com' },
  { company: 'Monzo',          slug: 'monzo',          ats: 'greenhouse', website: 'https://monzo.com' },
  { company: 'Starling Bank',  slug: 'starlingbank',   ats: 'greenhouse', website: 'https://starlingbank.com' },
  { company: 'SumUp',          slug: 'sumup',          ats: 'greenhouse', website: 'https://sumup.com' },
  { company: 'Mollie',         slug: 'mollie',         ats: 'greenhouse', website: 'https://mollie.com' },
  { company: 'Paddle',         slug: 'paddle',         ats: 'greenhouse', website: 'https://paddle.com' },
  { company: 'GoCardless',     slug: 'gocardless',     ats: 'greenhouse', website: 'https://gocardless.com' },
  { company: 'Codat',          slug: 'codat',          ats: 'greenhouse', website: 'https://codat.io' },
  { company: 'Sardine',        slug: 'sardine',        ats: 'greenhouse', website: 'https://sardine.ai' },
  { company: 'ComplyAdvantage', slug: 'complyadvantage', ats: 'greenhouse', website: 'https://complyadvantage.com' },
  { company: 'Chainalysis',    slug: 'chainalysis',    ats: 'greenhouse', website: 'https://chainalysis.com' },
  { company: 'Fireblocks',     slug: 'fireblocks',     ats: 'greenhouse', website: 'https://fireblocks.com' },
  { company: 'Anchorage Digital', slug: 'anchoragedigital', ats: 'greenhouse', website: 'https://anchorage.com' },
  { company: 'Copper',         slug: 'copper',         ats: 'greenhouse', website: 'https://copper.co' },
  { company: 'Bitpanda',       slug: 'bitpanda',       ats: 'greenhouse', website: 'https://bitpanda.com' },
  { company: 'Bitso',          slug: 'bitso',          ats: 'greenhouse', website: 'https://bitso.com' },

  // ── WealthTech & Wealth Management ──────────────────────────────────────
  { company: 'Addepar',        slug: 'addepar',        ats: 'greenhouse', website: 'https://addepar.com' },
  { company: 'Carta',          slug: 'carta',          ats: 'greenhouse', website: 'https://carta.com' },
  { company: 'Vestwell',       slug: 'vestwell',       ats: 'greenhouse', website: 'https://vestwell.com' },
  { company: 'Canoe Intelligence', slug: 'canoeintelligence', ats: 'greenhouse', website: 'https://canoeintelligence.com' },
  { company: 'Allocate',       slug: 'allocate',       ats: 'greenhouse', website: 'https://allocate.co' },
  { company: 'Titanbay',       slug: 'titanbay',       ats: 'greenhouse', website: 'https://titanbay.com' },
  { company: 'iCapital',       slug: 'icapitalnetwork', ats: 'greenhouse', website: 'https://icapitalnetwork.com' },
  { company: 'Moonfare',       slug: 'moonfare',       ats: 'greenhouse', website: 'https://moonfare.com' },
  { company: 'TIFIN',          slug: 'tifin',          ats: 'greenhouse', website: 'https://tifin.com' },
  { company: 'Farther',        slug: 'farther',        ats: 'greenhouse', website: 'https://farther.com' },
  { company: 'Facet Wealth',   slug: 'facetwealthinc', ats: 'greenhouse', website: 'https://facet.com' },
  { company: 'Betterment',     slug: 'betterment',     ats: 'greenhouse', website: 'https://betterment.com' },
  { company: 'InvestCloud',    slug: 'investcloud',    ats: 'greenhouse', website: 'https://investcloud.com' },
  { company: 'Landytech',      slug: 'landytech',      ats: 'greenhouse', website: 'https://landytech.com' },
  { company: 'Masttro',        slug: 'masttro',        ats: 'greenhouse', website: 'https://masttro.com' },
  { company: 'Equisoft',       slug: 'equisoft',       ats: 'greenhouse', website: 'https://equisoft.com' },
  { company: 'Bite Investments', slug: 'biteinvestments', ats: 'lever',   website: 'https://biteinvestments.com' },

  // ── VC / PE (Greenhouse only) ────────────────────────────────────────────
  { company: 'Bessemer Venture Partners', slug: 'bvp', ats: 'greenhouse', website: 'https://bvp.com' },

  // ── HR-Tech, SaaS & High-Tech ────────────────────────────────────────────
  { company: 'Personio',       slug: 'personio',       ats: 'greenhouse', website: 'https://personio.com' },
  { company: 'Factorial',      slug: 'factorial',      ats: 'greenhouse', website: 'https://factorialhr.com' },
  { company: 'Rippling',       slug: 'rippling',       ats: 'greenhouse', website: 'https://rippling.com' },
  { company: 'Remote.com',     slug: 'remote',         ats: 'greenhouse', website: 'https://remote.com' },
  { company: 'Velocity Global', slug: 'velocityglobal', ats: 'greenhouse', website: 'https://velocityglobal.com' },
  { company: 'Pendo',          slug: 'pendo',          ats: 'greenhouse', website: 'https://pendo.io' },
  { company: 'Outreach',       slug: 'outreach',       ats: 'greenhouse', website: 'https://outreach.io' },
  { company: 'Salesloft',      slug: 'salesloft',      ats: 'greenhouse', website: 'https://salesloft.com' },
  { company: 'ZoomInfo',       slug: 'zoominfo',       ats: 'greenhouse', website: 'https://zoominfo.com' },
  { company: 'Demandbase',     slug: 'demandbase',     ats: 'greenhouse', website: 'https://demandbase.com' },
  { company: 'Crossbeam',      slug: 'crossbeam',      ats: 'greenhouse', website: 'https://crossbeam.com' },
];
