-- Seed companies from career-pages.ts — idempotent via ON CONFLICT.
insert into companies (id, name, mono, slug, ats, website, sector, source) values
  ('c_melio', 'Melio', 'ME', 'melio', 'greenhouse', 'https://meliopayments.com', 'Israeli Fintech', 'config'),
  ('c_rapyd', 'Rapyd', 'RA', 'rapyd', 'lever', 'https://rapyd.net', 'Israeli Fintech', 'config'),
  ('c_payoneer', 'Payoneer', 'PA', 'payoneer', 'greenhouse', 'https://payoneer.com', 'Israeli Fintech', 'config'),
  ('c_pagaya', 'Pagaya', 'PA', 'pagaya', 'greenhouse', 'https://pagaya.com', 'Israeli Fintech', 'config'),
  ('c_etoro', 'eToro', 'ET', 'etoro', 'greenhouse', 'https://etoro.com', 'Israeli Fintech', 'config'),
  ('c_tipalti', 'Tipalti', 'TI', 'tipalti', 'greenhouse', 'https://tipalti.com', 'Israeli Fintech', 'config'),
  ('c_papayaglobal', 'Papaya Global', 'PG', 'papayaglobal', 'greenhouse', 'https://papayaglobal.com', 'Israeli Fintech', 'config'),
  ('c_riskified', 'Riskified', 'RI', 'riskified', 'greenhouse', 'https://riskified.com', 'Israeli Fintech', 'config'),
  ('c_nuvei', 'Nuvei', 'NU', 'nuvei', 'greenhouse', 'https://nuvei.com', 'Israeli Fintech', 'config'),
  ('c_fundbox', 'Fundbox', 'FU', 'fundbox', 'greenhouse', 'https://fundbox.com', 'Israeli Fintech', 'config'),
  ('c_globale', 'Global-e', 'GL', 'global-e', 'greenhouse', 'https://global-e.com', 'Israeli Fintech', 'config'),
  ('c_rewire', 'Rewire', 'RE', 'rewire', 'lever', 'https://rewire.to', 'Israeli Fintech', 'config'),
  ('c_tabby', 'Tabby', 'TA', 'tabby', 'greenhouse', 'https://tabby.ai', 'Israeli Fintech', 'config'),
  ('c_check', 'Check', 'CH', 'check', 'greenhouse', 'https://checkhq.com', 'Israeli Fintech', 'config'),
  ('c_stampli', 'Stampli', 'ST', 'stampli', 'greenhouse', 'https://stampli.com', 'Israeli Fintech', 'config'),
  ('c_bluesnap', 'BlueSnap', 'BL', 'bluesnap', 'greenhouse', 'https://bluesnap.com', 'Israeli Fintech', 'config'),
  ('c_meshpayments', 'Mesh Payments', 'MP', 'meshpayments', 'greenhouse', 'https://meshpayments.com', 'Israeli Fintech', 'config'),
  ('c_payrails', 'Payrails', 'PA', 'payrails', 'greenhouse', 'https://payrails.com', 'Israeli Fintech', 'config'),
  ('c_fundguard', 'FundGuard', 'FU', 'fundguard', 'greenhouse', 'https://fundguard.com', 'Israeli Fintech', 'config'),
  ('c_earnix', 'Earnix', 'EA', 'earnix', 'greenhouse', 'https://earnix.com', 'Israeli Fintech', 'config'),
  ('c_nayax', 'Nayax', 'NA', 'nayax', 'greenhouse', 'https://nayax.com', 'Israeli Fintech', 'config'),
  ('c_sentinels', 'Sentinels', 'SE', 'sentinels', 'greenhouse', 'https://sentinels.co', 'Israeli Fintech', 'config'),
  ('c_justt', 'Justt', 'JU', 'justt', 'greenhouse', 'https://justt.ai', 'Israeli Fintech', 'config'),
  ('c_appcharge', 'Appcharge', 'AP', 'appcharge', 'greenhouse', 'https://appcharge.com', 'Israeli Fintech', 'config'),
  ('c_okoora', 'Okoora', 'OK', 'okoora', 'greenhouse', 'https://okoora.com', 'Israeli Fintech', 'config'),
  ('c_obligo', 'Obligo', 'OB', 'obligo', 'greenhouse', 'https://obligo.com', 'Israeli Fintech', 'config'),
  ('c_lamaai', 'Lama AI', 'LA', 'lamaai', 'greenhouse', 'https://lama.ai', 'Israeli Fintech', 'config'),
  ('c_pontera', 'Pontera', 'PO', 'pontera', 'greenhouse', 'https://pontera.com', 'Israeli Fintech', 'config'),
  ('c_capitolis', 'Capitolis', 'CA', 'capitolis', 'greenhouse', 'https://capitolis.com', 'Israeli Fintech', 'config'),
  ('c_forter', 'Forter', 'FO', 'forter', 'greenhouse', 'https://forter.com', 'Israeli Fintech', 'config'),
  ('c_everc', 'EverC', 'EV', 'everc', 'greenhouse', 'https://everc.com', 'Israeli Fintech', 'config'),
  ('c_easysend', 'EasySend', 'EA', 'easysend', 'greenhouse', 'https://easysend.io', 'Israeli Fintech', 'config'),
  ('c_mondaycom', 'monday.com', 'MO', 'mondaydotcom', 'greenhouse', 'https://monday.com', 'Israeli Tech', 'config'),
  ('c_lemonade', 'Lemonade', 'LE', 'lemonade', 'greenhouse', 'https://lemonade.com', 'Israeli Tech', 'config'),
  ('c_wix', 'Wix', 'WI', 'wix', 'greenhouse', 'https://wix.com', 'Israeli Tech', 'config'),
  ('c_fiverr', 'Fiverr', 'FI', 'fiverr', 'greenhouse', 'https://fiverr.com', 'Israeli Tech', 'config'),
  ('c_lusha', 'Lusha', 'LU', 'lusha', 'greenhouse', 'https://lusha.com', 'Israeli Tech', 'config'),
  ('c_kaltura', 'Kaltura', 'KA', 'kaltura', 'greenhouse', 'https://kaltura.com', 'Israeli Tech', 'config'),
  ('c_silverfort', 'Silverfort', 'SI', 'silverfort', 'greenhouse', 'https://silverfort.com', 'Israeli Tech', 'config'),
  ('c_gett', 'Gett', 'GE', 'gett', 'greenhouse', 'https://gett.com', 'Israeli Tech', 'config'),
  ('c_trigo', 'Trigo', 'TR', 'trigovision', 'greenhouse', 'https://trigo.ai', 'Israeli Tech', 'config'),
  ('c_orcasecurity', 'Orca Security', 'OS', 'orcasecurity', 'greenhouse', 'https://orca.security', 'Israeli Tech', 'config'),
  ('c_snyk', 'Snyk', 'SN', 'snyk', 'greenhouse', 'https://snyk.io', 'Israeli Tech', 'config'),
  ('c_cloudinary', 'Cloudinary', 'CL', 'cloudinary', 'greenhouse', 'https://cloudinary.com', 'Israeli Tech', 'config'),
  ('c_similarweb', 'SimilarWeb', 'SI', 'similarweb', 'greenhouse', 'https://similarweb.com', 'Israeli Tech', 'config'),
  ('c_appsflyer', 'AppsFlyer', 'AP', 'appsflyer', 'greenhouse', 'https://appsflyer.com', 'Israeli Tech', 'config'),
  ('c_ironsource', 'IronSource', 'IR', 'ironsource', 'greenhouse', 'https://is.com', 'Israeli Tech', 'config'),
  ('c_outbrain', 'Outbrain', 'OU', 'outbrain', 'greenhouse', 'https://outbrain.com', 'Israeli Tech', 'config'),
  ('c_taboola', 'Taboola', 'TA', 'taboola', 'greenhouse', 'https://taboola.com', 'Israeli Tech', 'config'),
  ('c_walkme', 'WalkMe', 'WA', 'walkme', 'greenhouse', 'https://walkme.com', 'Israeli Tech', 'config'),
  ('c_playtika', 'Playtika', 'PL', 'playtika', 'greenhouse', 'https://playtika.com', 'Israeli Tech', 'config'),
  ('c_skai', 'Skai', 'SK', 'skai', 'greenhouse', 'https://skai.io', 'Israeli Tech', 'config'),
  ('c_bringg', 'Bringg', 'BR', 'bringg', 'greenhouse', 'https://bringg.com', 'Israeli Tech', 'config'),
  ('c_lightricks', 'Lightricks', 'LI', 'lightricks', 'greenhouse', 'https://lightricks.com', 'Israeli Tech', 'config'),
  ('c_activefence', 'ActiveFence', 'AC', 'activefence', 'greenhouse', 'https://activefence.com', 'Israeli Tech', 'config'),
  ('c_cybereason', 'Cybereason', 'CY', 'cybereason', 'greenhouse', 'https://cybereason.com', 'Israeli Tech', 'config'),
  ('c_gong', 'Gong', 'GO', 'gong', 'greenhouse', 'https://gong.io', 'Israeli Tech', 'config'),
  ('c_hibob', 'HiBob', 'HI', 'hibob', 'greenhouse', 'https://hibob.com', 'Israeli Tech', 'config'),
  ('c_zesty', 'Zesty', 'ZE', 'zesty', 'greenhouse', 'https://zesty.io', 'Israeli Tech', 'config'),
  ('c_syte', 'Syte', 'SY', 'syte', 'greenhouse', 'https://syte.ai', 'Israeli Tech', 'config'),
  ('c_buildots', 'Buildots', 'BU', 'buildots', 'greenhouse', 'https://buildots.com', 'Israeli Tech', 'config'),
  ('c_wiliot', 'Wiliot', 'WI', 'wiliot', 'greenhouse', 'https://wiliot.com', 'Israeli Tech', 'config'),
  ('c_namogoo', 'Namogoo', 'NA', 'namogoo', 'greenhouse', 'https://namogoo.com', 'Israeli Tech', 'config'),
  ('c_connecteam', 'Connecteam', 'CO', 'connecteam', 'greenhouse', 'https://connecteam.com', 'Israeli Tech', 'config'),
  ('c_elementor', 'Elementor', 'EL', 'elementor', 'greenhouse', 'https://elementor.com', 'Israeli Tech', 'config'),
  ('c_guesty', 'Guesty', 'GU', 'guesty', 'greenhouse', 'https://guesty.com', 'Israeli Tech', 'config'),
  ('c_credorax', 'Credorax', 'CR', 'credorax', 'greenhouse', 'https://credorax.com', 'Israeli Tech', 'config'),
  ('c_verbit', 'Verbit', 'VE', 'verbit', 'greenhouse', 'https://verbit.ai', 'Israeli Tech', 'config'),
  ('c_cellebrite', 'Cellebrite', 'CE', 'cellebrite', 'greenhouse', 'https://cellebrite.com', 'Israeli Tech', 'config'),
  ('c_frontegg', 'Frontegg', 'FR', 'frontegg', 'greenhouse', 'https://frontegg.com', 'Israeli Tech', 'config'),
  ('c_bigpanda', 'BigPanda', 'BI', 'bigpanda', 'greenhouse', 'https://bigpanda.io', 'Israeli Tech', 'config'),
  ('c_armis', 'Armis', 'AR', 'armis', 'greenhouse', 'https://armis.com', 'Israeli Tech', 'config'),
  ('c_varonis', 'Varonis', 'VA', 'varonis', 'greenhouse', 'https://varonis.com', 'Israeli Tech', 'config'),
  ('c_catonetworks', 'Cato Networks', 'CN', 'catonetworks', 'greenhouse', 'https://catonetworks.com', 'Israeli Tech', 'config'),
  ('c_sentinelone', 'SentinelOne', 'SE', 'sentinelone', 'greenhouse', 'https://sentinelone.com', 'Israeli Tech', 'config'),
  ('c_qonto', 'Qonto', 'QO', 'qonto', 'greenhouse', 'https://qonto.com', 'European Fintech', 'config'),
  ('c_alan', 'Alan', 'AL', 'alan', 'greenhouse', 'https://alan.com', 'European Fintech', 'config'),
  ('c_spendesk', 'Spendesk', 'SP', 'spendesk', 'greenhouse', 'https://spendesk.com', 'European Fintech', 'config'),
  ('c_payfit', 'Payfit', 'PA', 'payfit', 'greenhouse', 'https://payfit.com', 'European Fintech', 'config'),
  ('c_swile', 'Swile', 'SW', 'swile', 'greenhouse', 'https://swile.co', 'European Fintech', 'config'),
  ('c_alma', 'Alma', 'AL', 'alma', 'greenhouse', 'https://almapay.com', 'European Fintech', 'config'),
  ('c_pigment', 'Pigment', 'PI', 'pigment', 'greenhouse', 'https://pigment.app', 'European Fintech', 'config'),
  ('c_yousign', 'Yousign', 'YO', 'yousign', 'greenhouse', 'https://yousign.com', 'European Fintech', 'config'),
  ('c_agicap', 'Agicap', 'AG', 'agicap', 'greenhouse', 'https://agicap.com', 'European Fintech', 'config'),
  ('c_shine', 'Shine', 'SH', 'shine', 'greenhouse', 'https://shine.fr', 'European Fintech', 'config'),
  ('c_swan', 'Swan', 'SW', 'swan', 'greenhouse', 'https://swan.io', 'European Fintech', 'config'),
  ('c_memobank', 'Memo Bank', 'MB', 'memobank', 'greenhouse', 'https://memo.bank', 'European Fintech', 'config'),
  ('c_defacto', 'Defacto', 'DE', 'defacto', 'greenhouse', 'https://defacto.fr', 'European Fintech', 'config'),
  ('c_pleo', 'Pleo', 'PL', 'pleo', 'greenhouse', 'https://pleo.io', 'European Fintech', 'config'),
  ('c_moss', 'Moss', 'MO', 'moss', 'greenhouse', 'https://getmoss.com', 'European Fintech', 'config'),
  ('c_billie', 'Billie', 'BI', 'billie', 'greenhouse', 'https://billie.io', 'European Fintech', 'config'),
  ('c_mondu', 'Mondu', 'MO', 'mondu', 'greenhouse', 'https://mondu.ai', 'European Fintech', 'config'),
  ('c_liberis', 'Liberis', 'LI', 'liberis', 'greenhouse', 'https://liberis.com', 'European Fintech', 'config'),
  ('c_modulr', 'Modulr', 'MO', 'modulr', 'greenhouse', 'https://modulrfinance.com', 'European Fintech', 'config'),
  ('c_griffin', 'Griffin', 'GR', 'griffin', 'greenhouse', 'https://griffin.com', 'European Fintech', 'config'),
  ('c_primer', 'Primer', 'PR', 'primer', 'greenhouse', 'https://primer.io', 'European Fintech', 'config'),
  ('c_payhawk', 'Payhawk', 'PA', 'payhawk', 'greenhouse', 'https://payhawk.com', 'European Fintech', 'config'),
  ('c_soldo', 'Soldo', 'SO', 'soldo', 'greenhouse', 'https://soldo.com', 'European Fintech', 'config'),
  ('c_volt', 'Volt', 'VO', 'volt', 'greenhouse', 'https://volt.io', 'European Fintech', 'config'),
  ('c_yapily', 'Yapily', 'YA', 'yapily', 'greenhouse', 'https://yapily.com', 'European Fintech', 'config'),
  ('c_ledger', 'Ledger', 'LE', 'ledger', 'lever', 'https://ledger.com', 'European Fintech', 'config'),
  ('c_pennylane', 'Pennylane', 'PE', 'pennylane', 'lever', 'https://pennylane.com', 'European Fintech', 'config'),
  ('c_lydia', 'Lydia', 'LY', 'lydia', 'lever', 'https://lydia-app.com', 'European Fintech', 'config'),
  ('c_hokodo', 'Hokodo', 'HO', 'hokodo', 'lever', 'https://hokodo.co', 'European Fintech', 'config'),
  ('c_fintecture', 'Fintecture', 'FI', 'fintecture', 'lever', 'https://fintecture.com', 'European Fintech', 'config'),
  ('c_doctrine', 'Doctrine', 'DO', 'doctrine', 'lever', 'https://doctrine.fr', 'European Fintech', 'config'),
  ('c_indy', 'Indy', 'IN', 'indyapp', 'lever', 'https://indy.fr', 'European Fintech', 'config'),
  ('c_karmen', 'Karmen', 'KA', 'karmen', 'lever', 'https://karmen.io', 'European Fintech', 'config'),
  ('c_solarisbank', 'Solarisbank', 'SO', 'solarisbank', 'lever', 'https://solarisgroup.com', 'European Fintech', 'config'),
  ('c_traderepublic', 'Trade Republic', 'TR', 'traderepublic', 'greenhouse', 'https://traderepublic.com', 'European Fintech', 'config'),
  ('c_scalablecapital', 'Scalable Capital', 'SC', 'scalablecapital', 'greenhouse', 'https://scalable.capital', 'European Fintech', 'config'),
  ('c_taxfix', 'Taxfix', 'TA', 'taxfix', 'greenhouse', 'https://taxfix.de', 'European Fintech', 'config'),
  ('c_younited', 'Younited', 'YO', 'younited', 'greenhouse', 'https://younited-credit.com', 'European Fintech', 'config'),
  ('c_luko', 'Luko', 'LU', 'luko', 'greenhouse', 'https://luko.eu', 'European Fintech', 'config'),
  ('c_contentsquare', 'Contentsquare', 'CO', 'contentsquare', 'greenhouse', 'https://contentsquare.com', 'European Fintech', 'config'),
  ('c_dataiku', 'Dataiku', 'DA', 'dataiku', 'greenhouse', 'https://dataiku.com', 'European Fintech', 'config'),
  ('c_mirakl', 'Mirakl', 'MI', 'mirakl', 'greenhouse', 'https://mirakl.com', 'European Fintech', 'config'),
  ('c_october', 'October', 'OC', 'october', 'lever', 'https://october.eu', 'European Fintech', 'config'),
  ('c_wise', 'Wise', 'WI', 'wise', 'greenhouse', 'https://wise.com', 'Global Fintech', 'config'),
  ('c_checkoutcom', 'Checkout.com', 'CH', 'checkoutcom', 'greenhouse', 'https://checkout.com', 'Global Fintech', 'config'),
  ('c_airwallex', 'Airwallex', 'AI', 'airwallex', 'greenhouse', 'https://airwallex.com', 'Global Fintech', 'config'),
  ('c_deel', 'Deel', 'DE', 'deel', 'greenhouse', 'https://deel.com', 'Global Fintech', 'config'),
  ('c_ripple', 'Ripple', 'RI', 'ripple', 'greenhouse', 'https://ripple.com', 'Global Fintech', 'config'),
  ('c_stripe', 'Stripe', 'ST', 'stripe', 'greenhouse', 'https://stripe.com', 'Global Fintech', 'config'),
  ('c_brex', 'Brex', 'BR', 'brex', 'greenhouse', 'https://brex.com', 'Global Fintech', 'config'),
  ('c_marqeta', 'Marqeta', 'MA', 'marqeta', 'greenhouse', 'https://marqeta.com', 'Global Fintech', 'config'),
  ('c_plaid', 'Plaid', 'PL', 'plaid', 'greenhouse', 'https://plaid.com', 'Global Fintech', 'config'),
  ('c_nium', 'Nium', 'NI', 'nium', 'greenhouse', 'https://nium.com', 'Global Fintech', 'config'),
  ('c_flywire', 'Flywire', 'FL', 'flywire', 'greenhouse', 'https://flywire.com', 'Global Fintech', 'config'),
  ('c_dlocal', 'dLocal', 'DL', 'dlocal', 'greenhouse', 'https://dlocal.com', 'Global Fintech', 'config'),
  ('c_paysend', 'Paysend', 'PA', 'paysend', 'greenhouse', 'https://paysend.com', 'Global Fintech', 'config'),
  ('c_currencycloud', 'Currencycloud', 'CU', 'currencycloud', 'greenhouse', 'https://currencycloud.com', 'Global Fintech', 'config'),
  ('c_ebury', 'Ebury', 'EB', 'ebury', 'greenhouse', 'https://ebury.com', 'Global Fintech', 'config'),
  ('c_mambu', 'Mambu', 'MA', 'mambu', 'greenhouse', 'https://mambu.com', 'Global Fintech', 'config'),
  ('c_thoughtmachine', 'Thought Machine', 'TM', 'thoughtmachine', 'greenhouse', 'https://thoughtmachine.net', 'Global Fintech', 'config'),
  ('c_klarna', 'Klarna', 'KL', 'klarna', 'greenhouse', 'https://klarna.com', 'Global Fintech', 'config'),
  ('c_revolut', 'Revolut', 'RE', 'revolut', 'greenhouse', 'https://revolut.com', 'Global Fintech', 'config'),
  ('c_n26', 'N26', 'N2', 'n26', 'greenhouse', 'https://n26.com', 'Global Fintech', 'config'),
  ('c_monzo', 'Monzo', 'MO', 'monzo', 'greenhouse', 'https://monzo.com', 'Global Fintech', 'config'),
  ('c_starlingbank', 'Starling Bank', 'SB', 'starlingbank', 'greenhouse', 'https://starlingbank.com', 'Global Fintech', 'config'),
  ('c_sumup', 'SumUp', 'SU', 'sumup', 'greenhouse', 'https://sumup.com', 'Global Fintech', 'config'),
  ('c_mollie', 'Mollie', 'MO', 'mollie', 'greenhouse', 'https://mollie.com', 'Global Fintech', 'config'),
  ('c_paddle', 'Paddle', 'PA', 'paddle', 'greenhouse', 'https://paddle.com', 'Global Fintech', 'config'),
  ('c_gocardless', 'GoCardless', 'GO', 'gocardless', 'greenhouse', 'https://gocardless.com', 'Global Fintech', 'config'),
  ('c_codat', 'Codat', 'CO', 'codat', 'greenhouse', 'https://codat.io', 'Global Fintech', 'config'),
  ('c_sardine', 'Sardine', 'SA', 'sardine', 'greenhouse', 'https://sardine.ai', 'Global Fintech', 'config'),
  ('c_complyadvantage', 'ComplyAdvantage', 'CO', 'complyadvantage', 'greenhouse', 'https://complyadvantage.com', 'Global Fintech', 'config'),
  ('c_chainalysis', 'Chainalysis', 'CH', 'chainalysis', 'greenhouse', 'https://chainalysis.com', 'Global Fintech', 'config'),
  ('c_fireblocks', 'Fireblocks', 'FI', 'fireblocks', 'greenhouse', 'https://fireblocks.com', 'Global Fintech', 'config'),
  ('c_anchoragedigital', 'Anchorage Digital', 'AD', 'anchoragedigital', 'greenhouse', 'https://anchorage.com', 'Global Fintech', 'config'),
  ('c_copper', 'Copper', 'CO', 'copper', 'greenhouse', 'https://copper.co', 'Global Fintech', 'config'),
  ('c_bitpanda', 'Bitpanda', 'BI', 'bitpanda', 'greenhouse', 'https://bitpanda.com', 'Global Fintech', 'config'),
  ('c_bitso', 'Bitso', 'BI', 'bitso', 'greenhouse', 'https://bitso.com', 'Global Fintech', 'config'),
  ('c_adyen', 'Adyen', 'AD', 'adyen', 'greenhouse', 'https://adyen.com', 'Global Fintech', 'config'),
  ('c_ramp', 'Ramp', 'RA', 'ramp', 'greenhouse', 'https://ramp.com', 'Global Fintech', 'config'),
  ('c_mercury', 'Mercury', 'ME', 'mercury', 'greenhouse', 'https://mercury.com', 'Global Fintech', 'config'),
  ('c_bill', 'BILL', 'BI', 'billcom', 'greenhouse', 'https://bill.com', 'Global Fintech', 'config'),
  ('c_moderntreasury', 'Modern Treasury', 'MT', 'moderntreasury', 'greenhouse', 'https://moderntreasury.com', 'Global Fintech', 'config'),
  ('c_taxbit', 'Taxbit', 'TA', 'taxbit', 'greenhouse', 'https://taxbit.com', 'Global Fintech', 'config'),
  ('c_zerohash', 'Zero Hash', 'ZH', 'zerohash', 'greenhouse', 'https://zerohash.com', 'Global Fintech', 'config'),
  ('c_unit', 'Unit', 'UN', 'unit', 'greenhouse', 'https://unit.co', 'Global Fintech', 'config'),
  ('c_paysafe', 'Paysafe', 'PA', 'paysafe', 'greenhouse', 'https://paysafe.com', 'Global Fintech', 'config'),
  ('c_capchase', 'Capchase', 'CA', 'capchase', 'greenhouse', 'https://capchase.com', 'Global Fintech', 'config'),
  ('c_synctera', 'Synctera', 'SY', 'synctera', 'greenhouse', 'https://synctera.com', 'Global Fintech', 'config'),
  ('c_treasuryprime', 'Treasury Prime', 'TP', 'treasuryprime', 'greenhouse', 'https://treasuryprime.com', 'Global Fintech', 'config'),
  ('c_parafin', 'Parafin', 'PA', 'parafin', 'greenhouse', 'https://parafin.com', 'Global Fintech', 'config'),
  ('c_addepar', 'Addepar', 'AD', 'addepar', 'greenhouse', 'https://addepar.com', 'WealthTech', 'config'),
  ('c_carta', 'Carta', 'CA', 'carta', 'greenhouse', 'https://carta.com', 'WealthTech', 'config'),
  ('c_vestwell', 'Vestwell', 'VE', 'vestwell', 'greenhouse', 'https://vestwell.com', 'WealthTech', 'config'),
  ('c_canoeintelligence', 'Canoe Intelligence', 'CI', 'canoeintelligence', 'greenhouse', 'https://canoeintelligence.com', 'WealthTech', 'config'),
  ('c_allocate', 'Allocate', 'AL', 'allocate', 'greenhouse', 'https://allocate.co', 'WealthTech', 'config'),
  ('c_titanbay', 'Titanbay', 'TI', 'titanbay', 'greenhouse', 'https://titanbay.com', 'WealthTech', 'config'),
  ('c_icapital', 'iCapital', 'IC', 'icapitalnetwork', 'greenhouse', 'https://icapitalnetwork.com', 'WealthTech', 'config'),
  ('c_moonfare', 'Moonfare', 'MO', 'moonfare', 'greenhouse', 'https://moonfare.com', 'WealthTech', 'config'),
  ('c_tifin', 'TIFIN', 'TI', 'tifin', 'greenhouse', 'https://tifin.com', 'WealthTech', 'config'),
  ('c_farther', 'Farther', 'FA', 'farther', 'greenhouse', 'https://farther.com', 'WealthTech', 'config'),
  ('c_facetwealth', 'Facet Wealth', 'FW', 'facetwealthinc', 'greenhouse', 'https://facet.com', 'WealthTech', 'config'),
  ('c_betterment', 'Betterment', 'BE', 'betterment', 'greenhouse', 'https://betterment.com', 'WealthTech', 'config'),
  ('c_investcloud', 'InvestCloud', 'IN', 'investcloud', 'greenhouse', 'https://investcloud.com', 'WealthTech', 'config'),
  ('c_landytech', 'Landytech', 'LA', 'landytech', 'greenhouse', 'https://landytech.com', 'WealthTech', 'config'),
  ('c_masttro', 'Masttro', 'MA', 'masttro', 'greenhouse', 'https://masttro.com', 'WealthTech', 'config'),
  ('c_equisoft', 'Equisoft', 'EQ', 'equisoft', 'greenhouse', 'https://equisoft.com', 'WealthTech', 'config'),
  ('c_biteinvestments', 'Bite Investments', 'BI', 'biteinvestments', 'lever', 'https://biteinvestments.com', 'WealthTech', 'config'),
  ('c_altruist', 'Altruist', 'AL', 'altruist', 'greenhouse', 'https://altruist.com', 'WealthTech', 'config'),
  ('c_enfusion', 'Enfusion', 'EN', 'enfusion', 'greenhouse', 'https://enfusion.com', 'WealthTech', 'config'),
  ('c_arcesium', 'Arcesium', 'AR', 'arcesium', 'greenhouse', 'https://arcesium.com', 'WealthTech', 'config'),
  ('c_atomicfinancial', 'Atomic Financial', 'AF', 'atomicfinancial', 'greenhouse', 'https://atomicfi.com', 'WealthTech', 'config'),
  ('c_yieldx', 'YieldX', 'YI', 'yieldx', 'greenhouse', 'https://yieldx.app', 'WealthTech', 'config'),
  ('c_simonmarkets', 'Simon Markets', 'SM', 'simon-markets', 'greenhouse', 'https://simonmarkets.com', 'WealthTech', 'config'),
  ('c_insightpartners', 'Insight Partners', 'IP', 'insightpartners', 'greenhouse', 'https://insightpartners.com', 'VC / Growth', 'config'),
  ('c_bessemerventurepartners', 'Bessemer Venture Partners', 'BV', 'bvp', 'greenhouse', 'https://bvp.com', 'VC / Growth', 'config'),
  ('c_ourcrowd', 'OurCrowd', 'OU', 'ourcrowd', 'greenhouse', 'https://ourcrowd.com', 'VC / Growth', 'config'),
  ('c_team8', 'Team8', 'TE', 'team8', 'greenhouse', 'https://team8.vc', 'VC / Growth', 'config'),
  ('c_83north', '83North', '83', '83north', 'greenhouse', 'https://83north.com', 'VC / Growth', 'config'),
  ('c_targetglobal', 'Target Global', 'TG', 'targetglobal', 'greenhouse', 'https://target.global', 'VC / Growth', 'config'),
  ('c_tlvpartners', 'TLV Partners', 'TP', 'tlvpartners', 'greenhouse', 'https://tlv.partners', 'VC / Growth', 'config'),
  ('c_pitango', 'Pitango', 'PI', 'pitango', 'greenhouse', 'https://pitango.com', 'VC / Growth', 'config'),
  ('c_violaventures', 'Viola Ventures', 'VV', 'violaventures', 'greenhouse', 'https://viola-group.com', 'VC / Growth', 'config'),
  ('c_sequoiacapital', 'Sequoia Capital', 'SC', 'sequoiacap', 'greenhouse', 'https://sequoiacap.com', 'VC / Growth', 'config'),
  ('c_indexventures', 'Index Ventures', 'IV', 'indexventures', 'greenhouse', 'https://indexventures.com', 'VC / Growth', 'config'),
  ('c_baldertoncapital', 'Balderton Capital', 'BC', 'baldertoncapital', 'greenhouse', 'https://balderton.com', 'VC / Growth', 'config'),
  ('c_generalatlantic', 'General Atlantic', 'GA', 'generalatlantic', 'greenhouse', 'https://generalatlantic.com', 'VC / Growth', 'config'),
  ('c_atomico', 'Atomico', 'AT', 'atomico', 'greenhouse', 'https://atomico.com', 'VC / Growth', 'config'),
  ('c_northzone', 'Northzone', 'NO', 'northzone', 'greenhouse', 'https://northzone.com', 'VC / Growth', 'config'),
  ('c_headline', 'Headline', 'HE', 'headline', 'greenhouse', 'https://headline.com', 'VC / Growth', 'config'),
  ('c_accel', 'Accel', 'AC', 'accel', 'greenhouse', 'https://accel.com', 'VC / Growth', 'config'),
  ('c_personio', 'Personio', 'PE', 'personio', 'greenhouse', 'https://personio.com', 'HR-Tech / SaaS', 'config'),
  ('c_factorial', 'Factorial', 'FA', 'factorial', 'greenhouse', 'https://factorialhr.com', 'HR-Tech / SaaS', 'config'),
  ('c_rippling', 'Rippling', 'RI', 'rippling', 'greenhouse', 'https://rippling.com', 'HR-Tech / SaaS', 'config'),
  ('c_remotecom', 'Remote.com', 'RE', 'remote', 'greenhouse', 'https://remote.com', 'HR-Tech / SaaS', 'config'),
  ('c_velocityglobal', 'Velocity Global', 'VG', 'velocityglobal', 'greenhouse', 'https://velocityglobal.com', 'HR-Tech / SaaS', 'config'),
  ('c_pendo', 'Pendo', 'PE', 'pendo', 'greenhouse', 'https://pendo.io', 'HR-Tech / SaaS', 'config'),
  ('c_outreach', 'Outreach', 'OU', 'outreach', 'greenhouse', 'https://outreach.io', 'HR-Tech / SaaS', 'config'),
  ('c_salesloft', 'Salesloft', 'SA', 'salesloft', 'greenhouse', 'https://salesloft.com', 'HR-Tech / SaaS', 'config'),
  ('c_zoominfo', 'ZoomInfo', 'ZO', 'zoominfo', 'greenhouse', 'https://zoominfo.com', 'HR-Tech / SaaS', 'config'),
  ('c_demandbase', 'Demandbase', 'DE', 'demandbase', 'greenhouse', 'https://demandbase.com', 'HR-Tech / SaaS', 'config'),
  ('c_crossbeam', 'Crossbeam', 'CR', 'crossbeam', 'greenhouse', 'https://crossbeam.com', 'HR-Tech / SaaS', 'config')
on conflict (id) do nothing;
